// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://giiisznkfoztcpwkihjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpaWlzem5rZm96dGNwd2tpaGp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1ODk2NDYsImV4cCI6MjA2NzE2NTY0Nn0.2QTQA3yihBdfA28zRf5CIWU3YghacGaEcxJq5_vTaJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});